# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://chho-work.github.io/biolab/"

git_url = "https://github.com/chho-work/biolab/tree/main/"

def custom_doc_links(name): return None
